# Generated by Django 5.2.17 on 2026-09-10 07:25

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('training', 'Training / Workshop'), ('field_activity', 'Field Activity'), ('community_event', 'Community Event'), ('dialogue', 'Community Dialogue'), ('distribution', 'Distribution'), ('awareness', 'Awareness / Sensitization')], default='field_activity', max_length=30)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('sponsors', models.CharField(blank=True, help_text='Partners / funders, comma-separated', max_length=255)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date', 'display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('website_url', models.URLField(blank=True)),
                ('partnering_on', models.CharField(blank=True, help_text='e.g. Climate-smart agriculture, farmer training', max_length=255)),
                ('blurb', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualifications',
            field=models.CharField(blank=True, help_text='e.g. MSc Agronomy, University of Juba', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text='Leadership members are shown first, in the leadership section.'),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.activity')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
