# Generated by Django 5.2.17 on 2026-09-18 00:03

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_activity_partner_teammember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosscuttingtheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Which What We Do programme this project delivers, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.program'),
        ),
    ]
