# Generated by Django 5.2.17 on 2026-09-10 07:10

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('update', 'Update'), ('news', 'News'), ('field_story', 'Field Story'), ('event', 'Event'), ('press_statement', 'Press Statement'), ('publication', 'Publication / Report'), ('job', 'Job Advertisement')], default='update', max_length=30)),
                ('brief_description', models.CharField(help_text='Shown on the news feed card.', max_length=300)),
                ('body', models.TextField(help_text='Full detail shown on the article page.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='newsfeed/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube link — used as the card preview when there is no thumbnail.')),
                ('document', models.FileField(blank=True, help_text='Required for Press Statement and Publication posts. Shown as a download.', null=True, upload_to='newsfeed/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), apps.core.validators.validate_document_size])),
                ('is_published', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='If set and in the future, the post stays hidden until then.', null=True)),
                ('display_until', models.DateField(blank=True, help_text='Leave blank to keep the post visible indefinitely.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsfeed/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('youtube_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='newsfeed.newspost')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
