# Generated by Django 5.2.17 on 2026-09-10 06:48

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='SAFE', max_length=150)),
                ('organization_full_name', models.CharField(default='Sustainable Agriculture & Forest Environment', max_length=200)),
                ('tagline', models.CharField(default='Restoring Nature, Sustaining Life', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='ayom.mawien@safe-ss.org', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, default='admin@safengo.org', max_length=254)),
                ('phone_primary', models.CharField(blank=True, default='+211 922 144 884', max_length=40)),
                ('phone_secondary', models.CharField(blank=True, default='+211 989 446 688', max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, default='211989446688', help_text='Digits only, international format — used to build the wa.me link.', max_length=40)),
                ('address', models.CharField(blank=True, default='Juba, Central Equatoria, South Sudan', max_length=255)),
                ('office_hours', models.CharField(blank=True, default='Mon–Fri, 8:00 AM – 5:00 PM', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed link, optional.')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/safengo')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/safengo')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/safengo')),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_blurb', models.TextField(default='SAFE is a non-governmental organization dedicated to building resilient communities through sustainable agriculture and environmental stewardship in South Sudan.')),
                ('newsletter_blurb', models.CharField(default='Stay connected with our mission to restore nature and sustain life.', max_length=255)),
                ('meta_description', models.CharField(default='SAFE — Sustainable Agriculture & Forest Environment. Building climate-resilient communities in South Sudan through sustainable farming, food security, and environmental conservation.', max_length=255)),
                ('donate_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
