# Generated by Django 5.2.17 on 2026-09-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='SAFE at a glance', max_length=150)),
                ('intro', models.CharField(blank=True, default='The people and reach behind our work across South Sudan.', max_length=255)),
                ('staff_count', models.PositiveIntegerField(default=0, help_text='Full-time staff.')),
                ('field_staff_count', models.PositiveIntegerField(default=0, help_text='Field officers / extension workers.')),
                ('volunteers_count', models.PositiveIntegerField(default=0, help_text='Active volunteers.')),
                ('communities_served', models.PositiveIntegerField(default=0)),
                ('states_covered', models.PositiveIntegerField(default=0)),
                ('partners_count', models.PositiveIntegerField(default=0)),
                ('years_active', models.PositiveIntegerField(default=0)),
                ('auto_staff_count', models.BooleanField(default=True, help_text='Show the number of published team members instead of the fixed staff figure above.')),
                ('show_on_about', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization profile',
                'verbose_name_plural': 'Organization profile',
            },
        ),
    ]
