# Generated by Django 5.2.17 on 2026-09-10 06:48

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About SAFE', max_length=200)),
                ('hero_subtitle', models.CharField(default='Building resilient communities through sustainable agriculture and environmental stewardship.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('director_name', models.CharField(default='Ayom Mawien Arou', max_length=150)),
                ('director_role', models.CharField(default='Executive Director, SAFE', max_length=150)),
                ('director_photo', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('director_message', models.TextField(default='It is with great pride and humility that I welcome you to SAFE - Sustainable Agriculture and Forest Environment. Our organization was born from a deep commitment to addressing the interconnected challenges of food insecurity, environmental degradation, and climate vulnerability facing communities across South Sudan.\n\nThrough our work, we have witnessed the incredible resilience and determination of smallholder farmers who, despite facing numerous challenges, continue to nurture the land and feed their families. Our mission is to support these communities with the knowledge, resources, and partnerships they need to thrive sustainably.\n\nTogether, we are cultivating not just crops, but hope, resilience, and a sustainable future for generations to come.')),
                ('story_heading', models.CharField(default='Our Story', max_length=200)),
                ('story_body', models.TextField(default='SAFE was established in response to the urgent need for sustainable agricultural solutions in South Sudan. Our founders recognized that food security and environmental sustainability are inseparable, and that communities must be at the center of any meaningful change.\n\nWe work with smallholder farmers to build resilient agricultural systems that ensure sustainable agriculture and forest environment while protecting the environment. Our approach combines traditional knowledge with modern sustainable practices to increase yields and improve livelihoods.')),
                ('mission', models.TextField(default='To empower smallholder farming communities through sustainable agricultural practices, climate action, and environmental conservation, fostering resilience and food security.')),
                ('vision', models.TextField(default='A South Sudan where communities thrive through sustainable agriculture, environmental stewardship, and climate resilience, ensuring food security and prosperity for all.')),
                ('values_heading', models.CharField(default='Our Values', max_length=200)),
                ('values_intro', models.CharField(default='Guiding principles that shape our work and commitment to communities.', max_length=300)),
                ('team_heading', models.CharField(default='Our Team', max_length=200)),
                ('team_intro', models.CharField(default="The people driving SAFE's mission across South Sudan.", max_length=300)),
                ('legal_profile_heading', models.CharField(default='Legal and Operational Profile', max_length=200)),
                ('legal_profile', models.TextField(blank=True, default='SAFE is a registered non-governmental organization operating in South Sudan, with programmes in Warrap State, Northern Bahr el Ghazal State, and Central Equatoria. SAFE maintains a ZERO TOLERANCE policy for Sexual Exploitation, Abuse, and Harassment (SEAH).')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GetInvolvedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get Involved', max_length=200)),
                ('hero_subtitle', models.CharField(default='Join us in making a difference through donations, partnerships, or volunteering.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('intro', models.TextField(default='Together, we can build resilient communities and create sustainable futures for South Sudan. Your support enables us to reach more families and protect our environment.')),
                ('donate_heading', models.CharField(default='Donate', max_length=200)),
                ('donate_body', models.TextField(default='Your donation helps us provide seeds, tools, training, and support to farming communities across South Sudan. Every contribution makes a real difference in building sustainable livelihoods.')),
                ('volunteer_heading', models.CharField(default='Volunteer', max_length=200)),
                ('volunteer_body', models.TextField(default="SAFE welcomes volunteers who are passionate about sustainable agriculture, environmental conservation, and community development. Whether you have technical expertise or simply want to contribute your time and energy, there are many ways to get involved.\n\nSend us a note with your background, skills, and areas of interest, and we'll get back to you with opportunities that match your profile.")),
                ('partner_heading', models.CharField(default='Partner With Us', max_length=200)),
                ('partner_body', models.TextField(default='We welcome partnerships with organizations, businesses, and institutions that share our commitment to sustainable development. Together, we can amplify our impact and create lasting change.')),
                ('community_heading', models.CharField(default='Join Our Community', max_length=200)),
                ('community_body', models.TextField(default='Connect with like-minded individuals passionate about environmental conservation and community resilience. Subscribe to our newsletter for the latest updates on sustainable agriculture, forest conservation, and community empowerment.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Cultivating Resilience, Growing Futures', max_length=200)),
                ('hero_subtitle', models.CharField(default='Empowering communities in South Sudan through sustainable agriculture, climate action, and environmental conservation for a resilient future.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('hero_cta_label', models.CharField(default='Get Involved', max_length=60)),
                ('hero_cta_url', models.CharField(default='/get-involved/', max_length=200)),
                ('hero_secondary_label', models.CharField(blank=True, default='Our Work', max_length=60)),
                ('hero_secondary_url', models.CharField(blank=True, default='/what-we-do/', max_length=200)),
                ('intro_heading', models.CharField(default='Who We Are', max_length=200)),
                ('intro_body', models.TextField(default='SAFE is a non-governmental organization dedicated to building resilient communities through sustainable agriculture and environmental stewardship in South Sudan. We work at the intersection of agriculture, climate action, and community development, bringing together traditional knowledge and modern sustainable practices to create lasting impact.')),
                ('what_we_do_heading', models.CharField(default='What We Do', max_length=200)),
                ('what_we_do_intro', models.CharField(default='Our comprehensive approach to sustainable development and community empowerment.', max_length=300)),
                ('impact_heading', models.CharField(default='Our Impact', max_length=200)),
                ('impact_intro', models.CharField(default='Creating lasting change through sustainable development and community empowerment.', max_length=300)),
                ('projects_heading', models.CharField(default='Featured Projects', max_length=200)),
                ('projects_intro', models.CharField(default='Showcasing our sustainable farming and community agriculture projects.', max_length=300)),
                ('gallery_heading', models.CharField(default='Agriculture in Action', max_length=200)),
                ('gallery_intro', models.CharField(default='A visual journey through our work across South Sudan.', max_length=300)),
                ('testimonials_heading', models.CharField(default='Community Voices', max_length=200)),
                ('testimonials_intro', models.CharField(default='Stories of transformation from the communities we serve.', max_length=300)),
                ('cta_heading', models.CharField(default='Join Us in Making a Difference', max_length=200)),
                ('cta_body', models.TextField(default='Together, we can build resilient communities and create sustainable futures for South Sudan. Your support enables us to reach more families and protect our environment.')),
                ('cta_button_label', models.CharField(default='Get Involved Today', max_length=60)),
                ('cta_button_url', models.CharField(default='/get-involved/', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Impact', max_length=200)),
                ('hero_subtitle', models.CharField(default="Discover SAFE's measurable impact on food security, sustainable agriculture adoption, and environmental conservation across communities.", max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('intro', models.TextField(default='Creating lasting change through sustainable development and community empowerment.')),
                ('stats_heading', models.CharField(default='By the Numbers', max_length=200)),
                ('beneficiaries_heading', models.CharField(default='Target Beneficiaries', max_length=200)),
                ('beneficiaries_intro', models.CharField(default='Reaching communities across South Sudan.', max_length=300)),
                ('pathway_heading', models.CharField(default='Our Pathway to Change', max_length=200)),
                ('pathway_intro', models.CharField(default='Our pathway to sustainable impact and community transformation.', max_length=300)),
                ('voices_heading', models.CharField(default='Community Voices', max_length=200)),
                ('voices_intro', models.CharField(default='Stories of transformation from the communities we serve.', max_length=300)),
                ('gallery_heading', models.CharField(default='Visualizing the Transformation', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Community Resources', max_length=200)),
                ('hero_subtitle', models.CharField(default="Access SAFE's community resources, agricultural tools, training materials, and support programmes for sustainable farming and food security.", max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('intro', models.TextField(default='Supporting local communities with free seeds, organic goods, and agricultural resources.')),
                ('program_heading', models.CharField(default='Our Resource Distribution Programme', max_length=200)),
                ('program_body', models.TextField(default='SAFE is committed to supporting local communities with the resources they need to build sustainable agricultural practices. Our resource distribution programme provides:\nClimate-resilient seed varieties suited to local conditions\nBasic farming tools and equipment\nFarmer field school training and materials\nOngoing technical support and mentoring')),
                ('catalogue_heading', models.CharField(default='Approved Resources Available', max_length=200)),
                ('how_to_access_heading', models.CharField(default='How to Access Resources', max_length=200)),
                ('how_to_access_body', models.TextField(default='To request resources for your community, please fill out the form below. Our team will review your request and contact you to arrange distribution and provide any necessary training.')),
                ('request_form_heading', models.CharField(default='Request Community Resources', max_length=200)),
                ('request_form_intro', models.CharField(default='Tell us what your community needs and our team will be in touch.', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='What We Do', max_length=200)),
                ('hero_subtitle', models.CharField(default='Our comprehensive approach to sustainable development and community empowerment.', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), apps.core.validators.validate_image_size])),
                ('intro', models.TextField(default='We work with smallholder farmers to build resilient agricultural systems that ensure food security while protecting the environment. Our approach combines traditional knowledge with modern sustainable practices to increase yields and improve livelihoods.')),
                ('programs_heading', models.CharField(default='Our Programmes', max_length=200)),
                ('approach_heading', models.CharField(default='Our Approach', max_length=200)),
                ('approach_body', models.TextField(default='We work at the intersection of agriculture, climate action, and community development, bringing together traditional knowledge and modern sustainable practices to create lasting impact.')),
                ('themes_heading', models.CharField(default='Cross-Cutting Themes', max_length=200)),
                ('themes_intro', models.TextField(default='Our cross-cutting themes ensure that all our interventions are inclusive, safe, and sensitive to the complex dynamics of the communities we serve. We integrate these principles across all our programmes to maximize positive impact and ensure sustainable outcomes.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
