# Generated by Django 5.2.17 on 2026-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_heading',
            field=models.CharField(default='Latest News & Updates', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_intro',
            field=models.CharField(default='Field stories, events, and publications from across our work.', max_length=300),
        ),
    ]
